In [1]:
import illustris_python as il
import Catalogue 
import numpy as np
import params
import pandas as pd

In [2]:
basePath = '/home/tnguser/sims.TNG/TNG100-1/output/'
snapNum = 99 
h= 0.6774

In [3]:
Halos_cat = il.groupcat.loadHalos(basePath, snapNum, fields=['GroupCM', 'Group_R_Crit200', 'Group_M_Crit200'])

In [4]:
Header = il.groupcat.loadHeader(basePath, 99)

In [5]:
Halos_3R200 = Catalogue.select_halos_within_3r200(Halos_cat=Halos_cat, Halos_limits=params.Halos_limits,Header=Header, basePath=basePath, n_R200=3, particle='gas', N=99)

loading data for halo: 87 . . .
There are 1597124 particles to check distances . . . 
generating the catalogue for halo: 87
loading data for halo: 96 . . .
There are 1601789 particles to check distances . . . 
generating the catalogue for halo: 96
loading data for halo: 109 . . .
There are 1043151 particles to check distances . . . 
generating the catalogue for halo: 109
loading data for halo: 113 . . .
There are 1197513 particles to check distances . . . 
generating the catalogue for halo: 113
loading data for halo: 115 . . .
There are 1193744 particles to check distances . . . 
generating the catalogue for halo: 115
loading data for halo: 129 . . .
There are 1115994 particles to check distances . . . 
generating the catalogue for halo: 129
loading data for halo: 133 . . .
There are 879916 particles to check distances . . . 
generating the catalogue for halo: 133
loading data for halo: 135 . . .
There are 976532 particles to check distances . . . 
generating the catalogue for halo: 13

In [6]:
np.transpose(Halos_3R200)

array({87: {'pos_inside_3R200': array([[ 4078.97883809, 39946.40602933, 18410.89829134],
       [ 4080.14270938, 39946.95144893, 18411.54172728],
       [ 4079.54054365, 39947.62283143, 18411.23872953],
       ...,
       [ 3779.02829319, 39733.52720137, 18762.28386854],
       [ 4240.35102992, 39939.76965569, 19054.71319963],
       [ 4037.2698715 , 40125.66477799, 18333.40024769]]), 'pos_all_fof': array([[ 4078.97883809, 39946.40602933, 18410.89829134],
       [ 4080.14270938, 39946.95144893, 18411.54172728],
       [ 4079.54054365, 39947.62283143, 18411.23872953],
       ...,
       [ 3779.02829319, 39733.52720137, 18762.28386854],
       [ 4240.35102992, 39939.76965569, 19054.71319963],
       [ 4037.2698715 , 40125.66477799, 18333.40024769]]), 'mass_inside_3R200': array([1.41033423e-04, 1.38334013e-04, 1.07569162e-04, ...,
       6.06411850e-05, 1.05798164e-04, 6.69783403e-05], dtype=float32), 'mass_all_fof': array([1.41033423e-04, 1.38334013e-04, 1.07569162e-04, ...,
       6.064

In [7]:
df = pd.DataFrame(Halos_3R200)
df.to_pickle('Halos_3_R200_test.pkl')

In [10]:
len(df[87]['mass_inside_3R200']), len(df[87]['pos_all_fof'])

(1596109, 1597124)

In [18]:
center_test = Halos_cat['GroupCM'][87]

In [15]:
Header.keys()

dict_keys(['BoxSize', 'FlagDoubleprecision', 'Git_commit', 'Git_date', 'HubbleParam', 'Ngroups_ThisFile', 'Ngroups_Total', 'Nids_ThisFile', 'Nids_Total', 'Nsubgroups_ThisFile', 'Nsubgroups_Total', 'NumFiles', 'Omega0', 'OmegaLambda', 'Redshift', 'Time'])

In [20]:
CM_test_in = Catalogue.CM_3D(df[87]['pos_inside_3R200'], df[87]['mass_inside_3R200'], 
                center_test, Header['BoxSize'])

CM_test_out = Catalogue.CM_3D(df[87]['pos_all_fof'], df[87]['mass_all_fof'], 
                center_test, Header['BoxSize'])

In [21]:
CM_test_in, CM_test_out, center_test

(array([ 4269.71784362, 40208.92593097, 18457.49799176]),
 array([ 4269.9904371 , 40209.85010872, 18457.01462258]),
 array([ 2927.7424, 27293.996 , 12487.167 ], dtype=float32))